name: deploy


on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      
      - name: Gzip
        run: |
          tar -cvf picx.tar ./dist
      
      - name: SCP
        run: |
          apt install sshpass -y
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp ./picx.tar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }}:${{ secrets.REMOTE_PATH }}

